// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShopBackend.Data;

#nullable disable

namespace WebshopBackend.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20260520122613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("WebShopBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Öl",
                            ImageUrl = "wine01.jpeg",
                            Name = "Premium Olivenöl",
                            Price = 18.50m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Wein",
                            ImageUrl = "wine01.jpeg",
                            Name = "Rotwein Riserva",
                            Price = 24.90m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Wein",
                            ImageUrl = "wine01.jpeg",
                            Name = "Weißwein Chardonnay",
                            Price = 14.20m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Essig",
                            ImageUrl = "wine01.jpeg",
                            Name = "Balsamico Essig",
                            Price = 12.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
